import '@servicenow/sdk/global'
import { BusinessRule, ClientScript, Table, StringColumn, Record } from '@servicenow/sdk/core'

export const x_1234_keydemo_category = Table({
    name: 'x_1234_keydemo_category',
    schema: {
        name: StringColumn({ label: 'Name', mandatory: true, maxLength: 40 }),
        description: StringColumn({})
    },
    label: 'Keydemo Category',
})

Record({
    $id: '',
    table: 'x_1234_keydemo_category',
    data: {
        name: '1',
    },
})

//creates a client script that pops up 'Table loaded successfully!!' message everytime todo record is loaded
ClientScript({
    $id: Now.ID['cs0'],
    name: 'my_client_script',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`
             function onLoad() {
                                  g_form.addInfoMessage("Table loaded successfully!!")
                              }`,
})

//creates a business rule that pops up state change message whenever a todo record is updated
BusinessRule({
    $id: Now.ID['br0'],
    action: ['update', 'delete', 'insert'],
    table: 'incident',
    name: 'LogStateChange',
    order: 100,
    when: 'after',
    active: true,
    script: script`
             const { showStateUpdate } = require('./src/server/script.js')
                          showStateUpdate(current, previous)`,
    abort_action: false,
})
